In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
import sklearn
sklearn.show_versions()

System:
    python: 3.7.6 (default, Jan  8 2020, 20:23:39) [MSC v.1916 64 bit (AMD64)]
executable: C:\ProgramData\Anaconda3\python.exe
   machine: Windows-10-10.0.18362-SP0

Python dependencies:
          pip: 20.0.2
   setuptools: 45.2.0.post20200210
      sklearn: 0.23.2
        numpy: 1.18.1
        scipy: 1.4.1
       Cython: 0.29.15
       pandas: 1.0.1
   matplotlib: 3.1.3
       joblib: 0.14.1
threadpoolctl: 2.1.0

Built with OpenMP: True

In [3]:
Data=pd.read_csv('Heart_Disease.csv')

In [4]:
Data

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,57,0,0,140,241,0,1,123,1,0.2,1,0,3,0
299,45,1,3,110,264,0,1,132,0,1.2,1,0,3,0
300,68,1,0,144,193,1,1,141,0,3.4,1,2,3,0
301,57,1,0,130,131,0,1,115,1,1.2,1,1,3,0
302,57,0,1,130,236,0,0,174,0,0.0,1,1,2,0

In [5]:
Data.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [6]:
x=Data.drop('target',axis=1)
y=Data['target']

In [7]:
from sklearn.ensemble import RandomForestClassifier

In [8]:
RFC=RandomForestClassifier()

In [9]:
# DEFAULT HYPERPARAMETERS
RFC.get_params()

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'auto',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_impurity_split': None,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [11]:
RFC.fit(x_train,y_train);

In [12]:
RFC.fit(x_train,y_train)

RandomForestClassifier()

In [13]:
y_pred=RFC.predict(x_test)
y_pred

array([0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0], dtype=int64)

In [14]:
y_test

201    0
108    1
293    0
27     1
155    1
      ..
55     1
71     1
127    1
268    0
256    0
Name: target, Length: 61, dtype: int64

In [15]:
RFC.score(x_train,y_train)

1.0

In [16]:
# MEAN ACCURACY ON LABEL AND FEATURES
RFC.score(x_test,y_test)

0.7704918032786885

In [17]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

In [18]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.74      0.74      0.74        27
           1       0.79      0.79      0.79        34

    accuracy                           0.77        61
   macro avg       0.77      0.77      0.77        61
weighted avg       0.77      0.77      0.77        61

In [19]:
print(confusion_matrix(y_test,y_pred))

[[20  7]
 [ 7 27]]

In [20]:
print(accuracy_score(y_test,y_pred))

0.7704918032786885

In [21]:
np.random.seed(42)
for i in range(1,100):
    print(f"ESTIMATOR NUMBER:{i}")
    RFC=RandomForestClassifier(n_estimators=i).fit(x_train,y_train)
    print(f"MODEL ACCURACY ON TEST_SET:{RFC.score(x_test,y_test)*100:.2f}")
    print("")

ESTIMATOR NUMBER:1
MODEL ACCURACY ON TEST_SET:60.66

ESTIMATOR NUMBER:2
MODEL ACCURACY ON TEST_SET:70.49

ESTIMATOR NUMBER:3
MODEL ACCURACY ON TEST_SET:72.13

ESTIMATOR NUMBER:4
MODEL ACCURACY ON TEST_SET:65.57

ESTIMATOR NUMBER:5
MODEL ACCURACY ON TEST_SET:65.57

ESTIMATOR NUMBER:6
MODEL ACCURACY ON TEST_SET:70.49

ESTIMATOR NUMBER:7
MODEL ACCURACY ON TEST_SET:77.05

ESTIMATOR NUMBER:8
MODEL ACCURACY ON TEST_SET:68.85

ESTIMATOR NUMBER:9
MODEL ACCURACY ON TEST_SET:72.13

ESTIMATOR NUMBER:10
MODEL ACCURACY ON TEST_SET:72.13

ESTIMATOR NUMBER:11
MODEL ACCURACY ON TEST_SET:67.21

ESTIMATOR NUMBER:12
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:13
MODEL ACCURACY ON TEST_SET:68.85

ESTIMATOR NUMBER:14
MODEL ACCURACY ON TEST_SET:78.69

ESTIMATOR NUMBER:15
MODEL ACCURACY ON TEST_SET:70.49

ESTIMATOR NUMBER:16
MODEL ACCURACY ON TEST_SET:72.13

ESTIMATOR NUMBER:17
MODEL ACCURACY ON TEST_SET:80.33

ESTIMATOR NUMBER:18
MODEL ACCURACY ON TEST_SET:73.77

ESTIMATOR NUMBER:19
MODEL ACCURACY ON TEST_SET:80.33

ESTIMATOR NUMBER:20
MODEL ACCURACY ON TEST_SET:70.49

ESTIMATOR NUMBER:21
MODEL ACCURACY ON TEST_SET:73.77

ESTIMATOR NUMBER:22
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:23
MODEL ACCURACY ON TEST_SET:68.85

ESTIMATOR NUMBER:24
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:25
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:26
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:27
MODEL ACCURACY ON TEST_SET:77.05

ESTIMATOR NUMBER:28
MODEL ACCURACY ON TEST_SET:73.77

ESTIMATOR NUMBER:29
MODEL ACCURACY ON TEST_SET:73.77

ESTIMATOR NUMBER:30
MODEL ACCURACY ON TEST_SET:80.33

ESTIMATOR NUMBER:31
MODEL ACCURACY ON TEST_SET:78.69

ESTIMATOR NUMBER:32
MODEL ACCURACY ON TEST_SET:80.33

ESTIMATOR NUMBER:33
MODEL ACCURACY ON TEST_SET:73.77

ESTIMATOR NUMBER:34
MODEL ACCURACY ON TEST_SET:68.85

ESTIMATOR NUMBER:35
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:36
MODEL ACCURACY ON TEST_SET:77.05

ESTIMATOR NUMBER:37
MODEL ACCURACY ON TEST_SET:70.49

ESTIMATOR NUMBER:38
MODEL ACCURACY ON TEST_SET:73.77

ESTIMATOR NUMBER:39
MODEL ACCURACY ON TEST_SET:78.69

ESTIMATOR NUMBER:40
MODEL ACCURACY ON TEST_SET:73.77

ESTIMATOR NUMBER:41
MODEL ACCURACY ON TEST_SET:77.05

ESTIMATOR NUMBER:42
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:43
MODEL ACCURACY ON TEST_SET:80.33

ESTIMATOR NUMBER:44
MODEL ACCURACY ON TEST_SET:80.33

ESTIMATOR NUMBER:45
MODEL ACCURACY ON TEST_SET:78.69

ESTIMATOR NUMBER:46
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:47
MODEL ACCURACY ON TEST_SET:77.05

ESTIMATOR NUMBER:48
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:49
MODEL ACCURACY ON TEST_SET:78.69

ESTIMATOR NUMBER:50
MODEL ACCURACY ON TEST_SET:78.69

ESTIMATOR NUMBER:51
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:52
MODEL ACCURACY ON TEST_SET:73.77

ESTIMATOR NUMBER:53
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:54
MODEL ACCURACY ON TEST_SET:72.13

ESTIMATOR NUMBER:55
MODEL ACCURACY ON TEST_SET:77.05

ESTIMATOR NUMBER:56
MODEL ACCURACY ON TEST_SET:80.33

ESTIMATOR NUMBER:57
MODEL ACCURACY ON TEST_SET:80.33

ESTIMATOR NUMBER:58
MODEL ACCURACY ON TEST_SET:72.13

ESTIMATOR NUMBER:59
MODEL ACCURACY ON TEST_SET:77.05

ESTIMATOR NUMBER:60
MODEL ACCURACY ON TEST_SET:72.13

ESTIMATOR NUMBER:61
MODEL ACCURACY ON TEST_SET:77.05

ESTIMATOR NUMBER:62
MODEL ACCURACY ON TEST_SET:77.05

ESTIMATOR NUMBER:63
MODEL ACCURACY ON TEST_SET:80.33

ESTIMATOR NUMBER:64
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:65
MODEL ACCURACY ON TEST_SET:73.77

ESTIMATOR NUMBER:66
MODEL ACCURACY ON TEST_SET:78.69

ESTIMATOR NUMBER:67
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:68
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:69
MODEL ACCURACY ON TEST_SET:78.69

ESTIMATOR NUMBER:70
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:71
MODEL ACCURACY ON TEST_SET:77.05

ESTIMATOR NUMBER:72
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:73
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:74
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:75
MODEL ACCURACY ON TEST_SET:78.69

ESTIMATOR NUMBER:76
MODEL ACCURACY ON TEST_SET:78.69

ESTIMATOR NUMBER:77
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:78
MODEL ACCURACY ON TEST_SET:77.05

ESTIMATOR NUMBER:79
MODEL ACCURACY ON TEST_SET:77.05

ESTIMATOR NUMBER:80
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:81
MODEL ACCURACY ON TEST_SET:78.69

ESTIMATOR NUMBER:82
MODEL ACCURACY ON TEST_SET:78.69

ESTIMATOR NUMBER:83
MODEL ACCURACY ON TEST_SET:70.49

ESTIMATOR NUMBER:84
MODEL ACCURACY ON TEST_SET:78.69

ESTIMATOR NUMBER:85
MODEL ACCURACY ON TEST_SET:73.77

ESTIMATOR NUMBER:86
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:87
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:88
MODEL ACCURACY ON TEST_SET:73.77

ESTIMATOR NUMBER:89
MODEL ACCURACY ON TEST_SET:72.13

ESTIMATOR NUMBER:90
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:91
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:92
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:93
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:94
MODEL ACCURACY ON TEST_SET:78.69

ESTIMATOR NUMBER:95
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:96
MODEL ACCURACY ON TEST_SET:73.77

ESTIMATOR NUMBER:97
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:98
MODEL ACCURACY ON TEST_SET:78.69

ESTIMATOR NUMBER:99
MODEL ACCURACY ON TEST_SET:78.69

In [22]:
np.random.seed(42)
for i in range(10,100,10):
    print(f"ESTIMATOR NUMBER:{i}")
    RFC=RandomForestClassifier(n_estimators=i).fit(x_train,y_train)
    print(f"MODEL ACCURACY ON TEST_SET:{RFC.score(x_test,y_test)*100:.2f}")
    print("")

ESTIMATOR NUMBER:10
MODEL ACCURACY ON TEST_SET:68.85

ESTIMATOR NUMBER:20
MODEL ACCURACY ON TEST_SET:77.05

ESTIMATOR NUMBER:30
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:40
MODEL ACCURACY ON TEST_SET:75.41

ESTIMATOR NUMBER:50
MODEL ACCURACY ON TEST_SET:72.13

ESTIMATOR NUMBER:60
MODEL ACCURACY ON TEST_SET:72.13

ESTIMATOR NUMBER:70
MODEL ACCURACY ON TEST_SET:73.77

ESTIMATOR NUMBER:80
MODEL ACCURACY ON TEST_SET:77.05

ESTIMATOR NUMBER:90
MODEL ACCURACY ON TEST_SET:73.77

In [23]:
import pickle
pickle.dump(RFC,open("Random Forest Model.pkl","wb"))

In [24]:
Load=pickle.load(open("Random Forest Model.pkl","rb"))
Load.score(x_test,y_test)

0.7377049180327869